# Muration to Create a new Post
mutation NEW_POST {
  createPost(newPost:{
    title: "This is title of One",
    content: "This is and awesome post created from Apollo Server Running on the top of Expressjs and MongoDB.",
  }){
    id
    title
    content,
    createdAt
  }

}

# Query to Fetch all the Posts
query ALL_POSTS {
  allPosts{
    id
    title
    content
    createdAt
    updatedAt
  }
}

# Query to Fetch single Post by ID
query POST_BY_ID($id: ID!) {
  getPostById(id: $id) {
    title
    content
    createdAt
    updatedAt
    featuredImage
    author {
      id
      username
      firstName
    }
  }
}

# Mutation to Update the Post (Authentication Required)
mutation UPDATE_POST_BY_ID($id: ID!) {
  updatePost(
    id: $id
    updatedPost: {
      title: "Apollo Server is Awesome v0.2"
      content: "This is and awesome post created by Apollo Server Running on the top of Expressjs and MongoDB Updated."
    }
  ) {
    id
    title
    content
    featuredImage
    author {
      id
      username
    }
  }
}
