# Mutation to Register a new User in the Database
mutation REGISTER_USER {
  registerUser(
    newUser: {
      username: "nandymandy"
      password: "1234567890"
      firstName: "Narendra"
      lastName: "Maurya"
      email: "mauryanarendra09@gmail.com"
    }
  ) {
    token
    user {
      id
      email
      username
      lastName
      firstName
    }
  }
}

# Query to Authenticate the User 
query LOGIN_USER {
  loginUser(
      username: "nandymandy", 
      password: "123456790"
    ) {
    token
    user {
      id
      email
      firstName
      lastName
    }
  }
}

# Query to Fetch the Authenticated User by Token
query AUTH_USER {
  authUser{
    id
    lastName
    username
    firstName
  }
}
